### ISSUE TITLE
Get this error when I append the message to the sent folder using imap client

### ISSUE THREAD

**Issue by karthik67** [jstedfast/MailKit#251]
Hi, I get the below error when I append the message to the sent folder. the same code has worked before. But for some reason, it stopped working. 
Error is below:
The IMAP server replied to the 'APPEND' command with a 'BAD' response: Additional arguments found after last expected argument

My code is below:

```csharp
using (var imapClient = new ImapClient(new NullProtocolLogger()))
{
    var imapSecurity = emailConfiguration.IMAPSecurityConfiguration;
    var imapSecurityEnum = imapSecurity.Trim().ToLower().Contains("ssl")
        ? SecureSocketOptions.SslOnConnect
        : SecureSocketOptions.StartTls;

    imapClient.Connect(emailConfiguration.IMAPServer, emailConfiguration.IMAPPort,
        imapSecurityEnum);
    imapClient.AuthenticationMechanisms.Remove("XOAUTH2");
    imapClient.Authenticate(emailConfiguration.UserName,
        emailConfiguration.Password);
    
    var personalFolders = imapClient.GetFolders(imapClient.PersonalNamespaces[0]);
    
    var sentFolder = personalFolders.FirstOrDefault(r => r.Name.ToLower().Contains("sent"));
    if (sentFolder != null)
    {
        sentFolder.Open(FolderAccess.ReadWrite);
        sentFolder.Append(message);
        sentFolder.Close();
    }
}
```

**Comment by jstedfast** [comment]
Can you get me a protocol log? I need to see what the command is so that I can verify that it is correct.

On my IMAP servers, this works as expected so I cannot reproduce the error. I suspect your IMAP server is broken.

**Comment by karthik67** [comment]
where can I get the protocol log? BTW, I am trying to connect to yahoo imap server. Weird thing is it worked few minutes back. then it stopped working.
 
Date: Fri, 16 Oct 2015 12:17:16 -0700

**Comment by karthik67** [comment]
Hi, just another piece of information. we are evaluating another product and with that, yahoo works. I just tested Hotmail and Hotmail works fine. so just yahoo with the mailkit. thanks Karthik
 
Date: Fri, 16 Oct 2015 12:17:16 -0700

**Comment by jstedfast** [comment]
change this line:

```csharp
using (var imapClient = new ImapClient(new NullProtocolLogger()))
```

to this:

```csharp
using (var imapClient = new ImapClient(new ProtocolLogger ("imap.log"))
```

That will log all of the communications to a file called imap.log

**Comment by jstedfast** [comment]
I happen to have an IMAP account on yahoo.com, so I've tested it with the following MailKit commands and all of them work properly as expected:

```csharp
client.Inbox.Append (message);
client.Inbox.Append (message, MessageFlags.Seen);
client.Inbox.Append (message, MessageFlags.Seen, DateTimeOffset.Now);
client.Inbox.Append (message, MessageFlags.None, DateTimeOffset.Now);
```

They result in the following IMAP commands being sent to the server:

```
A00000005 APPEND Inbox {1174+}
```

```
A00000005 APPEND Inbox (\Seen) {1174+}
```

```
A00000005 APPEND Inbox (\Seen) "16-Oct-2015 16:01:08 -0400" {1174+}
```

```
A00000005 APPEND Inbox "16-Oct-2015 16:01:24 -0400" {1174+}
```

**Comment by karthik67** [comment]
let me try the same with the imap log.
 
Date: Fri, 16 Oct 2015 13:05:59 -0700

**Comment by karthik67** [comment]
hi Jeff,
I have attached the log file. It again worked. but second time onwards, it throws this error. Can you try more than once on your side as well?
Rgds
Karthik
 
Date: Fri, 16 Oct 2015 12:55:31 -0700

**Comment by jstedfast** [comment]
What versions of MimeKit and MailKit are you using? The problem appears to be a miscalculation of the size of the message.

**Comment by jstedfast** [comment]
Actually, that's not the problem. The number of bytes is being calculated correctly after all.

The problem seems to be that the message itself does not end with a CRLF.

My guess is that the Yahoo! mail server appended the message just fine in the first session's APPEND command, but the second session failed because their mailbox file did not end with a newline from the previous APPEND or something like that.

**Comment by karthik67** [comment]
Jeff, I will try adding a new line and give it a try. thanks.
 
Date: Fri, 16 Oct 2015 13:47:37 -0700

**Comment by jstedfast** [comment]
Once I add a newline to the end of your message, it works reliably.

**Comment by jstedfast** [comment]
I've landed a fix in MimeKit to make sure that writing a MimeMessage to a stream, the result will always end with a new-line.

Out of curiosity, what other IMAP library were you looking at?

**Comment by jstedfast** [comment]
I've released MimeKit 1.2.14 to NuGet with the fix for this bug.

I've also released MailKit 1.2.13 to NuGet.

**Comment by karthik67** [comment]
you are awesome. Thanks for the quick turn around.
 
Date: Mon, 19 Oct 2015 04:45:07 -0700

**Comment by edgiardina** [comment]
I am still seeing a flood of these errors connecting to YAHOO's IMAP; we are on Mailkit 2.0.3

**Comment by jstedfast** [comment]
@edgiardina do you know if your messages end with a newline? That seems to have been what the original problem was.

**Comment by edgiardina** [comment]
So we process thousands of messages a day via IMAP. The emails we process are varied and come from a large variety of customers and EMLs. I'm sure some end in newlines, but I doubt 80% of them do, which is what our error rate in IMAP to YAHOO is.

My working theory is that Yahoo's IMAP servers are behind a round robin DNS issue and 4 of their 5 reject messages frequently for some common denominator which I haven't determined. If you want to see a failing EML I can email you or PM you here, but in my testing most of the EMLs we have fail.

**Comment by jstedfast** [comment]
`message.WriteTo (stream);` should make sure that all messages end in a new-line. Could you verify that for a message that fails?

**Comment by edgiardina** [comment]
@jstedfast We are using `MimeMessage.Load()` ... grabbing a test message, the one I grabbed doesn't appear to have a newline at the end

![image](https://user-images.githubusercontent.com/3627193/39703570-7794cf9e-51d6-11e8-893d-73824125c21a.png)

**Comment by jstedfast** [comment]
Okay, then the problem is that when MimeKit parses an existing message, it doesn't enforce the message stream to end with a newline sequence because it wasn't there when the message was parsed.

It only enforces newlines when the message was constructed by code as in making use of `new MimeMessage (); ...`

**Comment by jstedfast** [comment]
I probably won't get a chance to make another release for another 2 weeks or so, but the above commits should fix the issue.

**Comment by edgiardina** [comment]
Thanks Jeffrey. adding it on the Imap append is perfect. I think the reason these emails don't have problems otherwise is that they're typically sent via SMTP not dropped in an IMAP folder. Appreciate the attention to this!

**Comment by jstedfast** [comment]
No problem.

**Comment by atiyka** [comment]
Hi,
I faced with the same issue. When I try to append a message I'm getting this error: _The IMAP server replied to the 'APPEND' command with a 'BAD' response: Additional arguments found after last expected argument._
I have the latest version of the library and I tried to append a forwarded message from a gmail account to an aol account. (I think that this cause the problem, because in other cases everything is working fine).
I attached the log file. Do you have any idea how to solve the append problem?

Thanks in advance!
[imap.log](https://github.com/jstedfast/MailKit/files/2926673/imap.log)

**Comment by jstedfast** [comment]
I don't see any problems based on the log. Do you have problems with any other IMAP servers?

**Comment by atiyka** [comment]
I tested now with another imap server (outlook) without any problem. Then probably the problem is something aol specific.
Thanks!
